apiVersion: v1
kind: Pod
metadata:
  name: toolbox
spec:
  containers:                            
  - image: andrejmaya/toolbox
    imagePullPolicy: Always
    name: toolbox
    ports:
      - containerPort: 5432
        protocol: TCP    